version: '3.8'

services:
  custom-centos:
    build:
      context: .
      dockerfile: Dockerfile
    port:
      - 80:80

    tty: true # Pour garder le conteneur ouvert en mode interactif
    stdin_open: true # Pour garder l'entrée standard ouverte
